name: Test GH Actions

on:
  push:
    branches:
      - main

jobs:
  create-file:
    name: Create File
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: docker pull alpine
