name: Test GH Actions

on:
  push:
    branches:
      - main

jobs:
  create-file:
    name: Create File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create File
        run: echo hello > world.txt

      - name: Create file in directory
        run: echo hello > ./directory/foo.txt

      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: ./world.txt

      - name: Upload file with directory
        uses: actions/upload-artifact@v2
        with:
          name: directory-test
          path: ./directory/foo.txt

  download-file:
    name: Download File
    runs-on: ubuntu-latest
    needs: create-file

    steps:
      - name: Download file
        uses: actions/download-artifact@v2
        with:
          name: test
          path: ./world.txt

      - name: Download file with directory
        uses: actions/download-artifact@v2
        with:
          name: directory-test
          path: ./foo.txt

      - name: Download file with directory - NO PATH
        uses: actions/download-artifact@v2
        with:
          name: directory-test

      - run: ls

      - run: cat ./world.txt

      - run: cat ./foo.txt